### GET / 
GET http://localhost:6001

### GET /sign-up.html
GET http://localhost:6001/sign-up.html

### POST /auth/signup
POST http://localhost:6001/auth/signup
Content-Type: application/json

{
  "name": "Jane Doe",
  "username": "Janedoe1",
  "email": "janedoe1@email.com",
  "password": "password"
}

### POST /auth/login
POST http://localhost:6001/auth/login
Content-Type: application/json

{
  "username": "Janedoe1",
  "password": "password"
}

### POST /auth/signup (ADD SECOND USER)
POST http://localhost:6001/auth/signup
Content-Type: application/json

{
  "name": "Joan Alves",
  "username": "Joan123alves",
  "email": "Joan125alves@email.com",
  "password": "password"
}

### POST /auth/login
POST http://localhost:6001/auth/login
Content-Type: application/json

{
  "username": "Joan123alves",
  "password": "password"
}

### POST /auth/signup -> negative path (Invalid email)
POST http://localhost:6001/auth/signup
Content-Type: application/json

{
  "name": "Joan Alves",
  "username": "Joan1alves",
  "email": "Joan1alves", 
  "password": "password"
}

### POST /auth/login -> negative path (INVALID PASSWORD)
POST http://localhost:6001/auth/login
Content-Type: application/json

{
  "username": "Janedoe1.2",
  "password": "passwordnotvalid"
}


### POST /auth/login -> negative path (INVALID USER)
POST http://localhost:6001/auth/login
Content-Type: application/json

{
  "username": "Janenotexist",
  "password": "passwordfornegativepath"
}


### POST /auth/login
POST http://localhost:6001/auth/login
Content-Type: application/json

{
  "username": "Janedoe82v",
  "password": "password"
}

### POST /auth/login (SECOND USER)
POST http://localhost:6001/auth/login
Content-Type: application/json

{
  "username": "Joan1alves",
  "password": "password"
}

### GET /app.html
GET http://localhost:6001/app.html

### POST /account/balance
POST http://localhost:6001/account/balance
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJKb2FuMTIzYWx2ZXMiLCJpYXQiOjE3NjE2NTE5MjAsImV4cCI6MTc2MTczODMyMH0.WI_WWFzibVIgTkZsK7-UGsaMD_nbQC5r23lbN6j2j3k
Content-Type: application/json

### PATCH /settings/username 
PATCH http://localhost:6001/settings/username 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJKb2FuMTIzYWx2ZXMiLCJpYXQiOjE3NjE2NTE5MjAsImV4cCI6MTc2MTczODMyMH0.WI_WWFzibVIgTkZsK7-UGsaMD_nbQC5r23lbN6j2j3k
Content-Type: application/json

{
  "newUsername": "Joan1alvesss",
}