### GET / 
GET http://localhost:6001

### GET /sign-up.html
GET http://localhost:6001/sign-up.html

### GET /app.html
GET http://localhost:6001/app.html

### POST /auth/signup
POST http://localhost:6001/auth/signup
Content-Type: application/json

{
  "name": "Jane Doe",
  "username": "Janedoe82v",
  "email": "janedoe82v@email.com",
  "password": "pasdswerna"
}

### POST /auth/login -> negative path (INVALID PASSWORD)
POST http://localhost:6001/auth/login
Content-Type: application/json

{
  "username": "Janedoe82v",
  "password": "passwordfornegativepath"
}

### POST /auth/login -> negative path (INVALID USER)
POST http://localhost:6001/auth/login
Content-Type: application/json

{
  "username": "Janenotexist",
  "password": "passwordfornegativepath"
}

### POST /auth/login
POST http://localhost:6001/auth/login
Content-Type: application/json

{
  "username": "Janedoe82v",
  "password": "pasdswerna"
}