### POST /auth/signup (ADD SECOND USER)
POST http://localhost:6001/auth/signup
Content-Type: application/json

{
  "name": "Valeria Alves",
  "username": "Valeria1.2alves",
  "email": "Valeria1.2@email.com",
  "password": "password"
}

### POST /auth/login
POST http://localhost:6001/auth/login
Content-Type: application/json

{
  "username": "Valeria1.2alves",
  "password": "password"
}

### PATCH /settings/username 
PATCH http://localhost:6001/settings/username 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsInVzZXJuYW1lIjoiVmFsZXJpYTEuMmFsdmVzIiwiaWF0IjoxNzYyMTgyMzA3LCJleHAiOjE3NjIyNjg3MDd9.P1k_TSX9ZyUE2pudeuVcZ3mLJTAI-L880Hwb8aoH7l4
Content-Type: application/json

{
  "newUsername": "Valeria1.1alves"
}

### PATCH /settings/username (SECOND TRY - SHOULD BE SUCCESSFUL FOR NOW - IT IS NOT LIMITED TO ONE YET)
PATCH http://localhost:6001/settings/username 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsInVzZXJuYW1lIjoiVmFsZXJpYTEuMmFsdmVzIiwiaWF0IjoxNzYyMTgyMzA3LCJleHAiOjE3NjIyNjg3MDd9.P1k_TSX9ZyUE2pudeuVcZ3mLJTAI-L880Hwb8aoH7l4
Content-Type: application/json

{
  "newUsername": "Valeria1.1.3"
}