name: Build and Test
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Set NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ".nvmrc"

      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
        # implement build output folder
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Set NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run dev

      - name: Run cypress tests
        run: npm run cy:run

      - name: Run playwright tests
        run: npm run pw:test
